name: Upload Python Package

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    tags:
      - "v*.*.*"

jobs:
  publish:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Mark github workspace as safe
        run: |
          git config --global --add safe.directory '*'
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          poetry_install_options: "--no-root --only main"
          pypi_token: ${{ secrets.PYPI_TOKEN }}