name: Upload Python Package

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        # see details (matrix, python-version, python-version-file, etc.)
        # https://github.com/actions/setup-python
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v4
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install --no-root --only test
      - name: Run the automated tests
        run: poetry run pytest -v

  publish:
    needs: test
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Mark github workspace as safe
        run: |
          git config --global --add safe.directory '*'
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          poetry_install_options: "--no-root --only main"
          pypi_token: ${{ secrets.PYPI_TOKEN }}